export const GET_COURSES = 'GET_COURSES'
export const POST_COURSES = 'POST_COURSES'
export const GET_DETAIL = 'GET_DETAIL'
export const GET_CATEGORIES = 'GET_CATEGORIES'

export const ADDFILTER = 'ADD_FILTER'

export const ORDER_BY_RATING = 'ORDER_BY_RATING'
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE'
export const ORDER_BY_PUBLISHED = 'ORDER_BY_PUBLISHED'

export const GET_FILTER_CATEGORY =  'GET_FILTER_CATEGORY'
export const FILTER_DIFFICULTY = 'FILTER_DIFFICULTY'
export const FILTER_DURATION = 'FILTER_DURATION'
export const FILTER_CATEGORY = 'FILTER_CATEGORY'
export const CLEAN_FILTERS = 'CLEAN_FILTERS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART'
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const HOME = 'HOME'
export const GET_WARNING = 'GET_WARNING'

export const GET_USERS = 'GET_USERS'
export const DISABLE_USER = 'DISABLE_USER'
